ALTER TABLE REG_RESOURCE_PROPERTY ADD ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE REG_RESOURCE_TAG ADD ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE REG_RESOURCE_COMMENT ADD ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE REG_RESOURCE_RATING ADD ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE UM_SHARED_USER_ROLE ADD ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT;
